### ISSUE TITLE
Overall review and ideas

### ISSUE THREAD

**Issue by flowcool** [jackkerouac/aphrodite#21]
Hey,

First: amazing tool I was looking at it! Thanks for it, I subscribe to get new about your releases and finally decided to go for it today...and..:

`# You need to download badge images and fonts from the repository release page
Visit: https://github.com/jackkerouac/aphrodite/releases
Download fonts.zip and images.zip
Extract these files to the respective directories`

This is not working (check in the final directory and you added some new pictures)

So few comments from my end:

- It would be good to have PUID / PGID features as I was stuck with access right and noticed you used 999 for UID at least
- Coming back to pictures and font, I would suggest to add it directly to the docker image, as I'm not sure to see the point to add it afterwards
- Same for every yaml files, let put everything to the docker image and copy it if not exists ? 
- rather than creating manually all directory, why not creating them during the installation ? (data, ./posters/original ./posters/working ./posters/modified) 

That being said, the docker compose would like:

```
services:
  aphrodite:
    image: ghcr.io/jackkerouac/aphrodite:latest
    container_name: aphrodite
    ports:
      - "2125:5000"
    volumes:
      - ${DOCKERCONFDIR}/aphrodite/:/app
  
    environment:
      # Basic environment variables - no need for .env file
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    restart: unless-stopped
```

And the config would be only:
mkdir aphrodite && cd aphrodite; tweak docker compose and run !
